-- Haujee Jewellery / JewelMS database schema (PostgreSQL).
-- GENERATED by scripts/generate-init-sql.mjs from drizzle/. Do not edit by hand:
-- change src/db/schema.ts, run `npm run db:generate`, then `npm run db:init-sql`.
--
-- Used to create a fresh database (docker-entrypoint-initdb.d). The admin user
-- and default settings are created by the app on its first start.

BEGIN;

-- Migration 0000_baseline
CREATE TABLE "audit_logs" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer,
	"action_type" varchar(50) NOT NULL,
	"details" jsonb,
	"ip_address" varchar(45),
	"user_agent" text,
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "customers" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"email" varchar(100),
	"address" text,
	"phone_number" varchar(20),
	"id_number" varchar(100),
	"risk_rating" varchar(20) DEFAULT 'Low' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "customers_id_number_unique" UNIQUE("id_number")
);
CREATE TABLE "odf" (
	"id" serial PRIMARY KEY NOT NULL,
	"odf_serial_number" serial NOT NULL,
	"date" timestamp with time zone DEFAULT now() NOT NULL,
	"customer_id" integer,
	"item_reserved_repair" text,
	"description" text,
	"comments" text,
	"weight" numeric(10, 3),
	"metal_type" varchar(50),
	"fineness" varchar(20),
	"amount" numeric(15, 2),
	"image_url" text,
	"file_url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "odf_items" (
	"id" serial PRIMARY KEY NOT NULL,
	"odf_id" integer NOT NULL,
	"description" text NOT NULL,
	"mass" numeric(10, 3) NOT NULL,
	"fineness" varchar(20) NOT NULL,
	"price" numeric(15, 2) DEFAULT '0.00',
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "orders" (
	"id" serial PRIMARY KEY NOT NULL,
	"order_number" serial NOT NULL,
	"customer_id" integer,
	"item_description" text,
	"estimated_weight" numeric(10, 3),
	"estimated_price" numeric(15, 2),
	"deposit" numeric(15, 2),
	"final_weight" numeric(10, 3),
	"final_price" numeric(15, 2),
	"status" varchar(20) DEFAULT 'Pending' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "receipts" (
	"id" serial PRIMARY KEY NOT NULL,
	"receipt_serial_number" serial NOT NULL,
	"sale_id" integer NOT NULL,
	"print_count" integer DEFAULT 0 NOT NULL,
	"file_url" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "roles_permissions" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" integer NOT NULL,
	"functionality" varchar(50) NOT NULL,
	"can_view" boolean DEFAULT false NOT NULL,
	"can_create" boolean DEFAULT false NOT NULL,
	"can_edit" boolean DEFAULT false NOT NULL,
	"can_delete" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "roles_permissions_user_id_functionality_unique" UNIQUE("user_id","functionality")
);
CREATE TABLE "sale_items" (
	"id" serial PRIMARY KEY NOT NULL,
	"sale_id" integer NOT NULL,
	"stock_id" integer,
	"barcode" varchar(100),
	"item_details" text,
	"qty" integer DEFAULT 1 NOT NULL,
	"unit_sales_price" numeric(15, 2),
	"amount" numeric(15, 2),
	"weight" numeric(10, 3),
	"fineness" varchar(20),
	"metal_type" varchar(50),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "sales" (
	"id" serial PRIMARY KEY NOT NULL,
	"customer_id" integer,
	"stock_id" integer,
	"datetime" timestamp with time zone DEFAULT now() NOT NULL,
	"payment_mode" varchar(20) NOT NULL,
	"cheque_number" varchar(50),
	"qty" integer DEFAULT 1 NOT NULL,
	"item_details" text,
	"weight" numeric(10, 3),
	"fineness" varchar(20),
	"unit_sales_price" numeric(15, 2),
	"amount" numeric(15, 2),
	"discount_amount" numeric(15, 2),
	"discount_percentage" numeric(5, 2),
	"vat_15" numeric(15, 2),
	"metal_type" varchar(50),
	"order_id" integer,
	"linked_odf_id" integer,
	"linked_commande_id" integer,
	"status" varchar(20) DEFAULT 'Completed' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
CREATE TABLE "settings" (
	"id" serial PRIMARY KEY NOT NULL,
	"key" varchar(100) NOT NULL,
	"value" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "settings_key_unique" UNIQUE("key")
);
CREATE TABLE "stock" (
	"id" serial PRIMARY KEY NOT NULL,
	"barcode" varchar(100) NOT NULL,
	"item_code" varchar(100),
	"category" varchar(100) NOT NULL,
	"sub_category" varchar(100),
	"stock_type" varchar(20) NOT NULL,
	"brand" varchar(100),
	"years_of_guarantee" integer DEFAULT 0,
	"serial_number" varchar(100),
	"metal_type" varchar(50),
	"fineness" varchar(20),
	"weight_grams" numeric(10, 3),
	"price" numeric(15, 2) DEFAULT '0.00',
	"price_net" numeric(15, 2) DEFAULT '0.00',
	"price_vat" numeric(15, 2) DEFAULT '0.00',
	"status" varchar(20) DEFAULT 'Disponible' NOT NULL,
	"sold_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "stock_barcode_unique" UNIQUE("barcode")
);
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"username" varchar(50) NOT NULL,
	"email" varchar(100) NOT NULL,
	"password_hash" text NOT NULL,
	"role" varchar(20) DEFAULT 'User' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_username_unique" UNIQUE("username"),
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "odf" ADD CONSTRAINT "odf_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "odf_items" ADD CONSTRAINT "odf_items_odf_id_odf_id_fk" FOREIGN KEY ("odf_id") REFERENCES "public"."odf"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "orders" ADD CONSTRAINT "orders_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "receipts" ADD CONSTRAINT "receipts_sale_id_sales_id_fk" FOREIGN KEY ("sale_id") REFERENCES "public"."sales"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "roles_permissions" ADD CONSTRAINT "roles_permissions_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "sale_items" ADD CONSTRAINT "sale_items_sale_id_sales_id_fk" FOREIGN KEY ("sale_id") REFERENCES "public"."sales"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "sale_items" ADD CONSTRAINT "sale_items_stock_id_stock_id_fk" FOREIGN KEY ("stock_id") REFERENCES "public"."stock"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "sales" ADD CONSTRAINT "sales_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "sales" ADD CONSTRAINT "sales_stock_id_stock_id_fk" FOREIGN KEY ("stock_id") REFERENCES "public"."stock"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "sales" ADD CONSTRAINT "sales_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "sales" ADD CONSTRAINT "sales_linked_odf_id_odf_id_fk" FOREIGN KEY ("linked_odf_id") REFERENCES "public"."odf"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "sales" ADD CONSTRAINT "sales_linked_commande_id_orders_id_fk" FOREIGN KEY ("linked_commande_id") REFERENCES "public"."orders"("id") ON DELETE set null ON UPDATE no action;
CREATE INDEX "idx_customers_id_number" ON "customers" USING btree ("id_number");
CREATE INDEX "idx_stock_item_code" ON "stock" USING btree ("item_code");

-- Migration 0001_notifications_token_version_unique_receipts
CREATE TABLE "notification_log" (
	"id" serial PRIMARY KEY NOT NULL,
	"kind" varchar(20) NOT NULL,
	"ref_id" integer NOT NULL,
	"channel" varchar(20) NOT NULL,
	"recipient" varchar(255),
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"error" text,
	"created_by" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
ALTER TABLE "users" ADD COLUMN "token_version" integer DEFAULT 0 NOT NULL;
ALTER TABLE "notification_log" ADD CONSTRAINT "notification_log_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;
CREATE INDEX "idx_notification_log_ref" ON "notification_log" USING btree ("kind","ref_id");
-- Merge duplicate receipts for the same sale before making sale_id unique:
-- keep the earliest (its serial number was issued first), add up print counts
-- and keep any stored file.
UPDATE "receipts" AS keep SET
	"print_count" = dup.total_prints,
	"file_url" = COALESCE(keep."file_url", dup.any_file)
FROM (
	SELECT "sale_id", MIN("id") AS keep_id, SUM("print_count") AS total_prints, MAX("file_url") AS any_file
	FROM "receipts" GROUP BY "sale_id" HAVING COUNT(*) > 1
) AS dup
WHERE keep."id" = dup.keep_id;
DELETE FROM "receipts" r USING "receipts" earlier
WHERE r."sale_id" = earlier."sale_id" AND r."id" > earlier."id";
ALTER TABLE "receipts" ADD CONSTRAINT "receipts_sale_id_unique" UNIQUE("sale_id");

-- Migration 0002_audit_log_action_length
ALTER TABLE "audit_logs" ALTER COLUMN "action_type" SET DATA TYPE varchar(255);
CREATE INDEX "idx_audit_logs_timestamp" ON "audit_logs" USING btree ("timestamp");

-- Migration 0003_sale_item_vat
ALTER TABLE "sale_items" ADD COLUMN "vat_15" numeric(15, 2);
-- Existing lines: a single-item sale's VAT is the sale's VAT; otherwise 15% of the line's net.
UPDATE "sale_items" AS si SET "vat_15" = CASE
	WHEN (SELECT COUNT(*) FROM "sale_items" x WHERE x."sale_id" = si."sale_id") = 1 AND s."vat_15" IS NOT NULL THEN s."vat_15"
	ELSE ROUND(COALESCE(si."amount", 0) * 0.15, 2)
END
FROM "sales" AS s
WHERE s."id" = si."sale_id" AND si."vat_15" IS NULL;

-- Record the migrations above as applied.
CREATE SCHEMA IF NOT EXISTS drizzle;
CREATE TABLE IF NOT EXISTS drizzle.__drizzle_migrations (id SERIAL PRIMARY KEY, hash text NOT NULL, created_at bigint);
INSERT INTO drizzle.__drizzle_migrations (hash, created_at) VALUES ('e581d710b948d3fe66add2ecddba690e5e53794d628d69056891459514d3ded7', 1790503081329);
INSERT INTO drizzle.__drizzle_migrations (hash, created_at) VALUES ('d4355d44f6d64c5fe270812b1bafdf685147bcbe21b41c1e333a35a57a090c08', 1790503209021);
INSERT INTO drizzle.__drizzle_migrations (hash, created_at) VALUES ('42520240590205b597499df4ac17dadff174d6dde6ad723010fe3aed739aadc7', 1790503455977);
INSERT INTO drizzle.__drizzle_migrations (hash, created_at) VALUES ('4a8d9a46306ee3fc20b2b361d35c22b7bdf16cd1e137e5f412bfc9cf2b46a441', 1790503651162);

COMMIT;
